// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pkg/proto/msg/base.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 心跳请求（客户端 → 服务端）
type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_pkg_proto_msg_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_base_proto_rawDescGZIP(), []int{0}
}

// 心跳响应（服务端 → 客户端）
type HeartbeatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 状态码：0=成功
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResp) Reset() {
	*x = HeartbeatResp{}
	mi := &file_pkg_proto_msg_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResp) ProtoMessage() {}

func (x *HeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResp.ProtoReflect.Descriptor instead.
func (*HeartbeatResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_base_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HeartbeatResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 登录请求（客户端 → 登录服）
type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // 用户名
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_pkg_proto_msg_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_base_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 登录响应（登录服 → 客户端）
type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                         // 状态码：0=成功，非0=失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                            // 提示信息
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                        // 登录令牌，后续请求携带
	PlayerId      int64                  `protobuf:"varint,4,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_pkg_proto_msg_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_base_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_pkg_proto_msg_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_base_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	PlayerId      uint64                 `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_pkg_proto_msg_base_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_base_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_base_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RegisterResp) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 错误响应（服务端 → 客户端）
type ErrorResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 错误码
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 错误描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResp) Reset() {
	*x = ErrorResp{}
	mi := &file_pkg_proto_msg_base_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResp) ProtoMessage() {}

func (x *ErrorResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_base_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResp.ProtoReflect.Descriptor instead.
func (*ErrorResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_base_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 发起匹配请求（客户端 → 游戏服）
type MatchStartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStartReq) Reset() {
	*x = MatchStartReq{}
	mi := &file_pkg_proto_msg_base_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartReq) ProtoMessage() {}

func (x *MatchStartReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_base_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartReq.ProtoReflect.Descriptor instead.
func (*MatchStartReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_base_proto_rawDescGZIP(), []int{7}
}

// 发起匹配响应（游戏服 → 客户端）
type MatchStartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                            // 业务状态码，0 成功，非 0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                               // 提示信息
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`           // 房间 ID，匹配成功时返回
	IsMatched     bool                   `protobuf:"varint,4,opt,name=is_matched,json=isMatched,proto3" json:"is_matched,omitempty"` // 是否已匹配成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStartResp) Reset() {
	*x = MatchStartResp{}
	mi := &file_pkg_proto_msg_base_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartResp) ProtoMessage() {}

func (x *MatchStartResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_base_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartResp.ProtoReflect.Descriptor instead.
func (*MatchStartResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_base_proto_rawDescGZIP(), []int{8}
}

func (x *MatchStartResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MatchStartResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MatchStartResp) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MatchStartResp) GetIsMatched() bool {
	if x != nil {
		return x.IsMatched
	}
	return false
}

// 取消匹配请求（客户端 → 游戏服）
type MatchCancelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCancelReq) Reset() {
	*x = MatchCancelReq{}
	mi := &file_pkg_proto_msg_base_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCancelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCancelReq) ProtoMessage() {}

func (x *MatchCancelReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_base_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCancelReq.ProtoReflect.Descriptor instead.
func (*MatchCancelReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_base_proto_rawDescGZIP(), []int{9}
}

// 取消匹配响应（游戏服 → 客户端）
type MatchCancelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码，0 成功，非 0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCancelResp) Reset() {
	*x = MatchCancelResp{}
	mi := &file_pkg_proto_msg_base_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCancelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCancelResp) ProtoMessage() {}

func (x *MatchCancelResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_base_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCancelResp.ProtoReflect.Descriptor instead.
func (*MatchCancelResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_base_proto_rawDescGZIP(), []int{10}
}

func (x *MatchCancelResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MatchCancelResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 清空匹配队列请求（客户端 → 游戏服）
type ClearMatchQueueReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearMatchQueueReq) Reset() {
	*x = ClearMatchQueueReq{}
	mi := &file_pkg_proto_msg_base_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearMatchQueueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearMatchQueueReq) ProtoMessage() {}

func (x *ClearMatchQueueReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_base_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearMatchQueueReq.ProtoReflect.Descriptor instead.
func (*ClearMatchQueueReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_base_proto_rawDescGZIP(), []int{11}
}

// 清空匹配队列响应（游戏服 → 客户端）
type ClearMatchQueueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码，0 成功，非 0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearMatchQueueResp) Reset() {
	*x = ClearMatchQueueResp{}
	mi := &file_pkg_proto_msg_base_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearMatchQueueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearMatchQueueResp) ProtoMessage() {}

func (x *ClearMatchQueueResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_base_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearMatchQueueResp.ProtoReflect.Descriptor instead.
func (*ClearMatchQueueResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_base_proto_rawDescGZIP(), []int{12}
}

func (x *ClearMatchQueueResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ClearMatchQueueResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pkg_proto_msg_base_proto protoreflect.FileDescriptor

const file_pkg_proto_msg_base_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/proto/msg/base.proto\x12\x03msg\"\x0e\n" +
	"\fHeartbeatReq\"5\n" +
	"\rHeartbeatResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"d\n" +
	"\tLoginResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1b\n" +
	"\tplayer_id\x18\x04 \x01(\x03R\bplayerId\"E\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"Q\n" +
	"\fRegisterResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x04R\bplayerId\"1\n" +
	"\tErrorResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x0f\n" +
	"\rMatchStartReq\"n\n" +
	"\x0eMatchStartResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"is_matched\x18\x04 \x01(\bR\tisMatched\"\x10\n" +
	"\x0eMatchCancelReq\"7\n" +
	"\x0fMatchCancelResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x14\n" +
	"\x12ClearMatchQueueReq\";\n" +
	"\x13ClearMatchQueueResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msgB\x0fZ\rpkg/proto/msgb\x06proto3"

var (
	file_pkg_proto_msg_base_proto_rawDescOnce sync.Once
	file_pkg_proto_msg_base_proto_rawDescData []byte
)

func file_pkg_proto_msg_base_proto_rawDescGZIP() []byte {
	file_pkg_proto_msg_base_proto_rawDescOnce.Do(func() {
		file_pkg_proto_msg_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_msg_base_proto_rawDesc), len(file_pkg_proto_msg_base_proto_rawDesc)))
	})
	return file_pkg_proto_msg_base_proto_rawDescData
}

var file_pkg_proto_msg_base_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_proto_msg_base_proto_goTypes = []any{
	(*HeartbeatReq)(nil),        // 0: msg.HeartbeatReq
	(*HeartbeatResp)(nil),       // 1: msg.HeartbeatResp
	(*LoginReq)(nil),            // 2: msg.LoginReq
	(*LoginResp)(nil),           // 3: msg.LoginResp
	(*RegisterReq)(nil),         // 4: msg.RegisterReq
	(*RegisterResp)(nil),        // 5: msg.RegisterResp
	(*ErrorResp)(nil),           // 6: msg.ErrorResp
	(*MatchStartReq)(nil),       // 7: msg.MatchStartReq
	(*MatchStartResp)(nil),      // 8: msg.MatchStartResp
	(*MatchCancelReq)(nil),      // 9: msg.MatchCancelReq
	(*MatchCancelResp)(nil),     // 10: msg.MatchCancelResp
	(*ClearMatchQueueReq)(nil),  // 11: msg.ClearMatchQueueReq
	(*ClearMatchQueueResp)(nil), // 12: msg.ClearMatchQueueResp
}
var file_pkg_proto_msg_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_msg_base_proto_init() }
func file_pkg_proto_msg_base_proto_init() {
	if File_pkg_proto_msg_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_msg_base_proto_rawDesc), len(file_pkg_proto_msg_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_msg_base_proto_goTypes,
		DependencyIndexes: file_pkg_proto_msg_base_proto_depIdxs,
		MessageInfos:      file_pkg_proto_msg_base_proto_msgTypes,
	}.Build()
	File_pkg_proto_msg_base_proto = out.File
	file_pkg_proto_msg_base_proto_goTypes = nil
	file_pkg_proto_msg_base_proto_depIdxs = nil
}
