// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pkg/proto/msg/game.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Point 网格坐标点，用于蛇身、食物等位置描述
type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"` // 横坐标（列），范围 0 ~ map_width-1
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"` // 纵坐标（行），范围 0 ~ map_height-1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_pkg_proto_msg_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_game_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// SnakeState 蛇的当前状态，用于游戏开始和帧同步时广播
type SnakeState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家 ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                  // 玩家昵称
	Body          []*Point               `protobuf:"bytes,3,rep,name=body,proto3" json:"body,omitempty"`                          // 蛇身坐标列表，索引 0 为蛇头
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`                       // 当前得分
	IsAlive       bool                   `protobuf:"varint,5,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`    // 是否存活
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnakeState) Reset() {
	*x = SnakeState{}
	mi := &file_pkg_proto_msg_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnakeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnakeState) ProtoMessage() {}

func (x *SnakeState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnakeState.ProtoReflect.Descriptor instead.
func (*SnakeState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_game_proto_rawDescGZIP(), []int{1}
}

func (x *SnakeState) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *SnakeState) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *SnakeState) GetBody() []*Point {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SnakeState) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SnakeState) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

// FoodState 食物状态
type FoodState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Point                 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"` // 食物所在坐标
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`      // 吃掉该食物获得的分数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodState) Reset() {
	*x = FoodState{}
	mi := &file_pkg_proto_msg_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodState) ProtoMessage() {}

func (x *FoodState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodState.ProtoReflect.Descriptor instead.
func (*FoodState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_game_proto_rawDescGZIP(), []int{2}
}

func (x *FoodState) GetPosition() *Point {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *FoodState) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// PlayerRank 玩家排名，用于游戏结束结算
type PlayerRank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家 ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                  // 玩家昵称
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`                       // 最终得分
	Rank          int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`                         // 排名，1 为第一名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRank) Reset() {
	*x = PlayerRank{}
	mi := &file_pkg_proto_msg_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRank) ProtoMessage() {}

func (x *PlayerRank) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRank.ProtoReflect.Descriptor instead.
func (*PlayerRank) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_game_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerRank) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerRank) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerRank) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PlayerRank) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// 方向操作请求（客户端 → 游戏服）
type GameOperationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     int32                  `protobuf:"varint,1,opt,name=direction,proto3" json:"direction,omitempty"` // 方向：1 上，2 下，3 左，4 右
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOperationReq) Reset() {
	*x = GameOperationReq{}
	mi := &file_pkg_proto_msg_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOperationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOperationReq) ProtoMessage() {}

func (x *GameOperationReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOperationReq.ProtoReflect.Descriptor instead.
func (*GameOperationReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_game_proto_rawDescGZIP(), []int{4}
}

func (x *GameOperationReq) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

// 方向操作响应（游戏服 → 客户端）
type GameOperationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码，0 成功，非 0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOperationResp) Reset() {
	*x = GameOperationResp{}
	mi := &file_pkg_proto_msg_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOperationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOperationResp) ProtoMessage() {}

func (x *GameOperationResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOperationResp.ProtoReflect.Descriptor instead.
func (*GameOperationResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameOperationResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GameOperationResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 房间信息查询请求（客户端 → 游戏服）
type RoomInfoQueryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间 ID，为空时查询自己所在房间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfoQueryReq) Reset() {
	*x = RoomInfoQueryReq{}
	mi := &file_pkg_proto_msg_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfoQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfoQueryReq) ProtoMessage() {}

func (x *RoomInfoQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfoQueryReq.ProtoReflect.Descriptor instead.
func (*RoomInfoQueryReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_game_proto_rawDescGZIP(), []int{6}
}

func (x *RoomInfoQueryReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// 游戏开始广播（游戏服 → 客户端）
// 房间内所有玩家同时收到，包含地图信息和双方初始状态
type GameStartNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapWidth      int32                  `protobuf:"varint,1,opt,name=map_width,json=mapWidth,proto3" json:"map_width,omitempty"`    // 地图宽度
	MapHeight     int32                  `protobuf:"varint,2,opt,name=map_height,json=mapHeight,proto3" json:"map_height,omitempty"` // 地图高度
	Snakes        []*SnakeState          `protobuf:"bytes,3,rep,name=snakes,proto3" json:"snakes,omitempty"`                         // 所有玩家的蛇初始状态
	Food          *FoodState             `protobuf:"bytes,4,opt,name=food,proto3" json:"food,omitempty"`                             // 第一个食物位置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStartNotify) Reset() {
	*x = GameStartNotify{}
	mi := &file_pkg_proto_msg_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStartNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStartNotify) ProtoMessage() {}

func (x *GameStartNotify) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStartNotify.ProtoReflect.Descriptor instead.
func (*GameStartNotify) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_game_proto_rawDescGZIP(), []int{7}
}

func (x *GameStartNotify) GetMapWidth() int32 {
	if x != nil {
		return x.MapWidth
	}
	return 0
}

func (x *GameStartNotify) GetMapHeight() int32 {
	if x != nil {
		return x.MapHeight
	}
	return 0
}

func (x *GameStartNotify) GetSnakes() []*SnakeState {
	if x != nil {
		return x.Snakes
	}
	return nil
}

func (x *GameStartNotify) GetFood() *FoodState {
	if x != nil {
		return x.Food
	}
	return nil
}

// 帧状态同步（游戏服 → 客户端）
// 每帧广播所有蛇的当前状态，客户端据此更新画面
type GameStateSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         int64                  `protobuf:"varint,1,opt,name=frame,proto3" json:"frame,omitempty"`  // 帧序号，从 1 开始递增
	Snakes        []*SnakeState          `protobuf:"bytes,2,rep,name=snakes,proto3" json:"snakes,omitempty"` // 所有玩家的蛇当前状态
	Food          *FoodState             `protobuf:"bytes,3,opt,name=food,proto3" json:"food,omitempty"`     // 当前食物位置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateSync) Reset() {
	*x = GameStateSync{}
	mi := &file_pkg_proto_msg_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateSync) ProtoMessage() {}

func (x *GameStateSync) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateSync.ProtoReflect.Descriptor instead.
func (*GameStateSync) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_game_proto_rawDescGZIP(), []int{8}
}

func (x *GameStateSync) GetFrame() int64 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *GameStateSync) GetSnakes() []*SnakeState {
	if x != nil {
		return x.Snakes
	}
	return nil
}

func (x *GameStateSync) GetFood() *FoodState {
	if x != nil {
		return x.Food
	}
	return nil
}

// 游戏结束广播（游戏服 → 客户端）
// 游戏结束时通知所有玩家最终排名
type GameOverNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranks         []*PlayerRank          `protobuf:"bytes,1,rep,name=ranks,proto3" json:"ranks,omitempty"` // 玩家排名列表，按排名升序排列
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOverNotify) Reset() {
	*x = GameOverNotify{}
	mi := &file_pkg_proto_msg_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOverNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOverNotify) ProtoMessage() {}

func (x *GameOverNotify) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOverNotify.ProtoReflect.Descriptor instead.
func (*GameOverNotify) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_game_proto_rawDescGZIP(), []int{9}
}

func (x *GameOverNotify) GetRanks() []*PlayerRank {
	if x != nil {
		return x.Ranks
	}
	return nil
}

// 排行榜查询请求（客户端 → 游戏服）
type RankQueryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankQueryReq) Reset() {
	*x = RankQueryReq{}
	mi := &file_pkg_proto_msg_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankQueryReq) ProtoMessage() {}

func (x *RankQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankQueryReq.ProtoReflect.Descriptor instead.
func (*RankQueryReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_game_proto_rawDescGZIP(), []int{10}
}

// 排行榜查询响应（游戏服 → 客户端）
type RankQueryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码，0 成功，非 0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 提示信息
	List          []*RankItem            `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`  // 排行榜条目列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankQueryResp) Reset() {
	*x = RankQueryResp{}
	mi := &file_pkg_proto_msg_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankQueryResp) ProtoMessage() {}

func (x *RankQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankQueryResp.ProtoReflect.Descriptor instead.
func (*RankQueryResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_game_proto_rawDescGZIP(), []int{11}
}

func (x *RankQueryResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RankQueryResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RankQueryResp) GetList() []*RankItem {
	if x != nil {
		return x.List
	}
	return nil
}

// RankItem 排行榜条目
type RankItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家 ID
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`                       // 玩家得分
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`                         // 排名，从 1 开始
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankItem) Reset() {
	*x = RankItem{}
	mi := &file_pkg_proto_msg_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankItem) ProtoMessage() {}

func (x *RankItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msg_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankItem.ProtoReflect.Descriptor instead.
func (*RankItem) Descriptor() ([]byte, []int) {
	return file_pkg_proto_msg_game_proto_rawDescGZIP(), []int{12}
}

func (x *RankItem) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *RankItem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RankItem) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

var File_pkg_proto_msg_game_proto protoreflect.FileDescriptor

const file_pkg_proto_msg_game_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/proto/msg/game.proto\x12\x03msg\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\x96\x01\n" +
	"\n" +
	"SnakeState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1e\n" +
	"\x04body\x18\x03 \x03(\v2\n" +
	".msg.PointR\x04body\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x19\n" +
	"\bis_alive\x18\x05 \x01(\bR\aisAlive\"I\n" +
	"\tFoodState\x12&\n" +
	"\bposition\x18\x01 \x01(\v2\n" +
	".msg.PointR\bposition\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"o\n" +
	"\n" +
	"PlayerRank\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\"0\n" +
	"\x10GameOperationReq\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\x05R\tdirection\"9\n" +
	"\x11GameOperationResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"+\n" +
	"\x10RoomInfoQueryReq\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x9a\x01\n" +
	"\x0fGameStartNotify\x12\x1b\n" +
	"\tmap_width\x18\x01 \x01(\x05R\bmapWidth\x12\x1d\n" +
	"\n" +
	"map_height\x18\x02 \x01(\x05R\tmapHeight\x12'\n" +
	"\x06snakes\x18\x03 \x03(\v2\x0f.msg.SnakeStateR\x06snakes\x12\"\n" +
	"\x04food\x18\x04 \x01(\v2\x0e.msg.FoodStateR\x04food\"r\n" +
	"\rGameStateSync\x12\x14\n" +
	"\x05frame\x18\x01 \x01(\x03R\x05frame\x12'\n" +
	"\x06snakes\x18\x02 \x03(\v2\x0f.msg.SnakeStateR\x06snakes\x12\"\n" +
	"\x04food\x18\x03 \x01(\v2\x0e.msg.FoodStateR\x04food\"7\n" +
	"\x0eGameOverNotify\x12%\n" +
	"\x05ranks\x18\x01 \x03(\v2\x0f.msg.PlayerRankR\x05ranks\"\x0e\n" +
	"\fRankQueryReq\"X\n" +
	"\rRankQueryResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\x04list\x18\x03 \x03(\v2\r.msg.RankItemR\x04list\"Q\n" +
	"\bRankItem\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rankB\x0fZ\rpkg/proto/msgb\x06proto3"

var (
	file_pkg_proto_msg_game_proto_rawDescOnce sync.Once
	file_pkg_proto_msg_game_proto_rawDescData []byte
)

func file_pkg_proto_msg_game_proto_rawDescGZIP() []byte {
	file_pkg_proto_msg_game_proto_rawDescOnce.Do(func() {
		file_pkg_proto_msg_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_msg_game_proto_rawDesc), len(file_pkg_proto_msg_game_proto_rawDesc)))
	})
	return file_pkg_proto_msg_game_proto_rawDescData
}

var file_pkg_proto_msg_game_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_proto_msg_game_proto_goTypes = []any{
	(*Point)(nil),             // 0: msg.Point
	(*SnakeState)(nil),        // 1: msg.SnakeState
	(*FoodState)(nil),         // 2: msg.FoodState
	(*PlayerRank)(nil),        // 3: msg.PlayerRank
	(*GameOperationReq)(nil),  // 4: msg.GameOperationReq
	(*GameOperationResp)(nil), // 5: msg.GameOperationResp
	(*RoomInfoQueryReq)(nil),  // 6: msg.RoomInfoQueryReq
	(*GameStartNotify)(nil),   // 7: msg.GameStartNotify
	(*GameStateSync)(nil),     // 8: msg.GameStateSync
	(*GameOverNotify)(nil),    // 9: msg.GameOverNotify
	(*RankQueryReq)(nil),      // 10: msg.RankQueryReq
	(*RankQueryResp)(nil),     // 11: msg.RankQueryResp
	(*RankItem)(nil),          // 12: msg.RankItem
}
var file_pkg_proto_msg_game_proto_depIdxs = []int32{
	0,  // 0: msg.SnakeState.body:type_name -> msg.Point
	0,  // 1: msg.FoodState.position:type_name -> msg.Point
	1,  // 2: msg.GameStartNotify.snakes:type_name -> msg.SnakeState
	2,  // 3: msg.GameStartNotify.food:type_name -> msg.FoodState
	1,  // 4: msg.GameStateSync.snakes:type_name -> msg.SnakeState
	2,  // 5: msg.GameStateSync.food:type_name -> msg.FoodState
	3,  // 6: msg.GameOverNotify.ranks:type_name -> msg.PlayerRank
	12, // 7: msg.RankQueryResp.list:type_name -> msg.RankItem
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_proto_msg_game_proto_init() }
func file_pkg_proto_msg_game_proto_init() {
	if File_pkg_proto_msg_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_msg_game_proto_rawDesc), len(file_pkg_proto_msg_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_msg_game_proto_goTypes,
		DependencyIndexes: file_pkg_proto_msg_game_proto_depIdxs,
		MessageInfos:      file_pkg_proto_msg_game_proto_msgTypes,
	}.Build()
	File_pkg_proto_msg_game_proto = out.File
	file_pkg_proto_msg_game_proto_goTypes = nil
	file_pkg_proto_msg_game_proto_depIdxs = nil
}
