// 游戏服务 protobuf 定义
// 包含匹配、房间管理三个 RPC 接口

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pkg/proto/rpc/game.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Point 网格坐标点
type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// SnakeState 蛇的当前状态
type SnakeState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Body          []*Point               `protobuf:"bytes,3,rep,name=body,proto3" json:"body,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	IsAlive       bool                   `protobuf:"varint,5,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnakeState) Reset() {
	*x = SnakeState{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnakeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnakeState) ProtoMessage() {}

func (x *SnakeState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnakeState.ProtoReflect.Descriptor instead.
func (*SnakeState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{1}
}

func (x *SnakeState) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *SnakeState) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *SnakeState) GetBody() []*Point {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SnakeState) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SnakeState) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

// FoodState 食物状态
type FoodState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Point                 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodState) Reset() {
	*x = FoodState{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodState) ProtoMessage() {}

func (x *FoodState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodState.ProtoReflect.Descriptor instead.
func (*FoodState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{2}
}

func (x *FoodState) GetPosition() *Point {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *FoodState) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// PlayerInfo 玩家信息
type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家 ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                  // 玩家昵称
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`                       // 玩家分数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerInfo) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerInfo) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// StartMatchRequest 发起匹配请求
type StartMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家 ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                  // 玩家昵称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMatchRequest) Reset() {
	*x = StartMatchRequest{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchRequest) ProtoMessage() {}

func (x *StartMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchRequest.ProtoReflect.Descriptor instead.
func (*StartMatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{4}
}

func (x *StartMatchRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *StartMatchRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

// StartMatchResponse 发起匹配响应
type StartMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                            // 业务状态码，0 成功，非 0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                               // 提示信息
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`           // 房间 ID，匹配成功时返回
	IsMatched     bool                   `protobuf:"varint,4,opt,name=is_matched,json=isMatched,proto3" json:"is_matched,omitempty"` // 是否已匹配成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMatchResponse) Reset() {
	*x = StartMatchResponse{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchResponse) ProtoMessage() {}

func (x *StartMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchResponse.ProtoReflect.Descriptor instead.
func (*StartMatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{5}
}

func (x *StartMatchResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StartMatchResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *StartMatchResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StartMatchResponse) GetIsMatched() bool {
	if x != nil {
		return x.IsMatched
	}
	return false
}

// CancelMatchRequest 取消匹配请求
type CancelMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchRequest) Reset() {
	*x = CancelMatchRequest{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchRequest) ProtoMessage() {}

func (x *CancelMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchRequest.ProtoReflect.Descriptor instead.
func (*CancelMatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{6}
}

func (x *CancelMatchRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// CancelMatchResponse 取消匹配响应
type CancelMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码，0 成功，非 0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchResponse) Reset() {
	*x = CancelMatchResponse{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchResponse) ProtoMessage() {}

func (x *CancelMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchResponse.ProtoReflect.Descriptor instead.
func (*CancelMatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{7}
}

func (x *CancelMatchResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CancelMatchResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// GetRoomInfoRequest 获取房间信息请求
type GetRoomInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomInfoRequest) Reset() {
	*x = GetRoomInfoRequest{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInfoRequest) ProtoMessage() {}

func (x *GetRoomInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRoomInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{8}
}

func (x *GetRoomInfoRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// GetRoomInfoResponse 获取房间信息响应
type GetRoomInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                               // 业务状态码，0 成功，非 0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                                  // 提示信息
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`              // 房间 ID
	Players       []*PlayerInfo          `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`                          // 房间内玩家列表
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                           // 房间状态，0 等待中，1 游戏中，2 已结束
	GameStatus    int32                  `protobuf:"varint,6,opt,name=game_status,json=gameStatus,proto3" json:"game_status,omitempty"` // 游戏阶段：1 未开始，2 进行中，3 暂停，4 已结束
	Frame         int64                  `protobuf:"varint,7,opt,name=frame,proto3" json:"frame,omitempty"`                             // 当前帧序号
	Snakes        []*SnakeState          `protobuf:"bytes,8,rep,name=snakes,proto3" json:"snakes,omitempty"`                            // 所有蛇的当前状态
	Food          *FoodState             `protobuf:"bytes,9,opt,name=food,proto3" json:"food,omitempty"`                                // 当前食物位置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomInfoResponse) Reset() {
	*x = GetRoomInfoResponse{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInfoResponse) ProtoMessage() {}

func (x *GetRoomInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRoomInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{9}
}

func (x *GetRoomInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRoomInfoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetRoomInfoResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetRoomInfoResponse) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GetRoomInfoResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetRoomInfoResponse) GetGameStatus() int32 {
	if x != nil {
		return x.GameStatus
	}
	return 0
}

func (x *GetRoomInfoResponse) GetFrame() int64 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *GetRoomInfoResponse) GetSnakes() []*SnakeState {
	if x != nil {
		return x.Snakes
	}
	return nil
}

func (x *GetRoomInfoResponse) GetFood() *FoodState {
	if x != nil {
		return x.Food
	}
	return nil
}

// PlayerOperationRequest 玩家游戏操作请求
type PlayerOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家 ID
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`        // 房间 ID
	Direction     int32                  `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"`               // 方向：1 上，2 下，3 左，4 右
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerOperationRequest) Reset() {
	*x = PlayerOperationRequest{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOperationRequest) ProtoMessage() {}

func (x *PlayerOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOperationRequest.ProtoReflect.Descriptor instead.
func (*PlayerOperationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerOperationRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerOperationRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PlayerOperationRequest) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

// PlayerOperationResponse 玩家游戏操作响应
type PlayerOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码，0 成功，非 0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerOperationResponse) Reset() {
	*x = PlayerOperationResponse{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOperationResponse) ProtoMessage() {}

func (x *PlayerOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOperationResponse.ProtoReflect.Descriptor instead.
func (*PlayerOperationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerOperationResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PlayerOperationResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// PlayerOfflineRequest 玩家离线通知请求
type PlayerOfflineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 离线玩家 ID
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`        // 房间 ID，网关已知时传入；为空时游戏服自行查找
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerOfflineRequest) Reset() {
	*x = PlayerOfflineRequest{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerOfflineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOfflineRequest) ProtoMessage() {}

func (x *PlayerOfflineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOfflineRequest.ProtoReflect.Descriptor instead.
func (*PlayerOfflineRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerOfflineRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerOfflineRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// PlayerOfflineResponse 玩家离线通知响应
type PlayerOfflineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码，0 成功，非 0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerOfflineResponse) Reset() {
	*x = PlayerOfflineResponse{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerOfflineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOfflineResponse) ProtoMessage() {}

func (x *PlayerOfflineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOfflineResponse.ProtoReflect.Descriptor instead.
func (*PlayerOfflineResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{13}
}

func (x *PlayerOfflineResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PlayerOfflineResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// GetGlobalRankRequest 查询全服排行榜请求
type GetGlobalRankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalRankRequest) Reset() {
	*x = GetGlobalRankRequest{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalRankRequest) ProtoMessage() {}

func (x *GetGlobalRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalRankRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalRankRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{14}
}

// GetGlobalRankResponse 查询全服排行榜响应
type GetGlobalRankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码，0 成功，非 0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 提示信息
	List          []*RankItem            `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`  // 排行榜条目列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalRankResponse) Reset() {
	*x = GetGlobalRankResponse{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalRankResponse) ProtoMessage() {}

func (x *GetGlobalRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalRankResponse.ProtoReflect.Descriptor instead.
func (*GetGlobalRankResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{15}
}

func (x *GetGlobalRankResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGlobalRankResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetGlobalRankResponse) GetList() []*RankItem {
	if x != nil {
		return x.List
	}
	return nil
}

// RankItem 排行榜条目
type RankItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家 ID
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`                       // 玩家得分
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`                         // 排名，从 1 开始
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankItem) Reset() {
	*x = RankItem{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankItem) ProtoMessage() {}

func (x *RankItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankItem.ProtoReflect.Descriptor instead.
func (*RankItem) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{16}
}

func (x *RankItem) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *RankItem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RankItem) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// ClearMatchQueueRequest 清空匹配队列请求
type ClearMatchQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearMatchQueueRequest) Reset() {
	*x = ClearMatchQueueRequest{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearMatchQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearMatchQueueRequest) ProtoMessage() {}

func (x *ClearMatchQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearMatchQueueRequest.ProtoReflect.Descriptor instead.
func (*ClearMatchQueueRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{17}
}

// ClearMatchQueueResponse 清空匹配队列响应
type ClearMatchQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码，0 成功，非 0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearMatchQueueResponse) Reset() {
	*x = ClearMatchQueueResponse{}
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearMatchQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearMatchQueueResponse) ProtoMessage() {}

func (x *ClearMatchQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearMatchQueueResponse.ProtoReflect.Descriptor instead.
func (*ClearMatchQueueResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_game_proto_rawDescGZIP(), []int{18}
}

func (x *ClearMatchQueueResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ClearMatchQueueResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pkg_proto_rpc_game_proto protoreflect.FileDescriptor

const file_pkg_proto_rpc_game_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/proto/rpc/game.proto\x12\x03rpc\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\x96\x01\n" +
	"\n" +
	"SnakeState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1e\n" +
	"\x04body\x18\x03 \x03(\v2\n" +
	".rpc.PointR\x04body\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x19\n" +
	"\bis_alive\x18\x05 \x01(\bR\aisAlive\"I\n" +
	"\tFoodState\x12&\n" +
	"\bposition\x18\x01 \x01(\v2\n" +
	".rpc.PointR\bposition\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"[\n" +
	"\n" +
	"PlayerInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"L\n" +
	"\x11StartMatchRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\"r\n" +
	"\x12StartMatchResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"is_matched\x18\x04 \x01(\bR\tisMatched\"1\n" +
	"\x12CancelMatchRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\";\n" +
	"\x13CancelMatchResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"-\n" +
	"\x12GetRoomInfoRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x9b\x02\n" +
	"\x13GetRoomInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12)\n" +
	"\aplayers\x18\x04 \x03(\v2\x0f.rpc.PlayerInfoR\aplayers\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1f\n" +
	"\vgame_status\x18\x06 \x01(\x05R\n" +
	"gameStatus\x12\x14\n" +
	"\x05frame\x18\a \x01(\x03R\x05frame\x12'\n" +
	"\x06snakes\x18\b \x03(\v2\x0f.rpc.SnakeStateR\x06snakes\x12\"\n" +
	"\x04food\x18\t \x01(\v2\x0e.rpc.FoodStateR\x04food\"l\n" +
	"\x16PlayerOperationRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\x05R\tdirection\"?\n" +
	"\x17PlayerOperationResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"L\n" +
	"\x14PlayerOfflineRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"=\n" +
	"\x15PlayerOfflineResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x16\n" +
	"\x14GetGlobalRankRequest\"`\n" +
	"\x15GetGlobalRankResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\x04list\x18\x03 \x03(\v2\r.rpc.RankItemR\x04list\"Q\n" +
	"\bRankItem\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\"\x18\n" +
	"\x16ClearMatchQueueRequest\"?\n" +
	"\x17ClearMatchQueueResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xfc\x03\n" +
	"\vGameService\x12=\n" +
	"\n" +
	"StartMatch\x12\x16.rpc.StartMatchRequest\x1a\x17.rpc.StartMatchResponse\x12@\n" +
	"\vCancelMatch\x12\x17.rpc.CancelMatchRequest\x1a\x18.rpc.CancelMatchResponse\x12@\n" +
	"\vGetRoomInfo\x12\x17.rpc.GetRoomInfoRequest\x1a\x18.rpc.GetRoomInfoResponse\x12L\n" +
	"\x0fPlayerOperation\x12\x1b.rpc.PlayerOperationRequest\x1a\x1c.rpc.PlayerOperationResponse\x12F\n" +
	"\rPlayerOffline\x12\x19.rpc.PlayerOfflineRequest\x1a\x1a.rpc.PlayerOfflineResponse\x12F\n" +
	"\rGetGlobalRank\x12\x19.rpc.GetGlobalRankRequest\x1a\x1a.rpc.GetGlobalRankResponse\x12L\n" +
	"\x0fClearMatchQueue\x12\x1b.rpc.ClearMatchQueueRequest\x1a\x1c.rpc.ClearMatchQueueResponseB\x13Z\x11pkg/proto/rpc;rpcb\x06proto3"

var (
	file_pkg_proto_rpc_game_proto_rawDescOnce sync.Once
	file_pkg_proto_rpc_game_proto_rawDescData []byte
)

func file_pkg_proto_rpc_game_proto_rawDescGZIP() []byte {
	file_pkg_proto_rpc_game_proto_rawDescOnce.Do(func() {
		file_pkg_proto_rpc_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_rpc_game_proto_rawDesc), len(file_pkg_proto_rpc_game_proto_rawDesc)))
	})
	return file_pkg_proto_rpc_game_proto_rawDescData
}

var file_pkg_proto_rpc_game_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_pkg_proto_rpc_game_proto_goTypes = []any{
	(*Point)(nil),                   // 0: rpc.Point
	(*SnakeState)(nil),              // 1: rpc.SnakeState
	(*FoodState)(nil),               // 2: rpc.FoodState
	(*PlayerInfo)(nil),              // 3: rpc.PlayerInfo
	(*StartMatchRequest)(nil),       // 4: rpc.StartMatchRequest
	(*StartMatchResponse)(nil),      // 5: rpc.StartMatchResponse
	(*CancelMatchRequest)(nil),      // 6: rpc.CancelMatchRequest
	(*CancelMatchResponse)(nil),     // 7: rpc.CancelMatchResponse
	(*GetRoomInfoRequest)(nil),      // 8: rpc.GetRoomInfoRequest
	(*GetRoomInfoResponse)(nil),     // 9: rpc.GetRoomInfoResponse
	(*PlayerOperationRequest)(nil),  // 10: rpc.PlayerOperationRequest
	(*PlayerOperationResponse)(nil), // 11: rpc.PlayerOperationResponse
	(*PlayerOfflineRequest)(nil),    // 12: rpc.PlayerOfflineRequest
	(*PlayerOfflineResponse)(nil),   // 13: rpc.PlayerOfflineResponse
	(*GetGlobalRankRequest)(nil),    // 14: rpc.GetGlobalRankRequest
	(*GetGlobalRankResponse)(nil),   // 15: rpc.GetGlobalRankResponse
	(*RankItem)(nil),                // 16: rpc.RankItem
	(*ClearMatchQueueRequest)(nil),  // 17: rpc.ClearMatchQueueRequest
	(*ClearMatchQueueResponse)(nil), // 18: rpc.ClearMatchQueueResponse
}
var file_pkg_proto_rpc_game_proto_depIdxs = []int32{
	0,  // 0: rpc.SnakeState.body:type_name -> rpc.Point
	0,  // 1: rpc.FoodState.position:type_name -> rpc.Point
	3,  // 2: rpc.GetRoomInfoResponse.players:type_name -> rpc.PlayerInfo
	1,  // 3: rpc.GetRoomInfoResponse.snakes:type_name -> rpc.SnakeState
	2,  // 4: rpc.GetRoomInfoResponse.food:type_name -> rpc.FoodState
	16, // 5: rpc.GetGlobalRankResponse.list:type_name -> rpc.RankItem
	4,  // 6: rpc.GameService.StartMatch:input_type -> rpc.StartMatchRequest
	6,  // 7: rpc.GameService.CancelMatch:input_type -> rpc.CancelMatchRequest
	8,  // 8: rpc.GameService.GetRoomInfo:input_type -> rpc.GetRoomInfoRequest
	10, // 9: rpc.GameService.PlayerOperation:input_type -> rpc.PlayerOperationRequest
	12, // 10: rpc.GameService.PlayerOffline:input_type -> rpc.PlayerOfflineRequest
	14, // 11: rpc.GameService.GetGlobalRank:input_type -> rpc.GetGlobalRankRequest
	17, // 12: rpc.GameService.ClearMatchQueue:input_type -> rpc.ClearMatchQueueRequest
	5,  // 13: rpc.GameService.StartMatch:output_type -> rpc.StartMatchResponse
	7,  // 14: rpc.GameService.CancelMatch:output_type -> rpc.CancelMatchResponse
	9,  // 15: rpc.GameService.GetRoomInfo:output_type -> rpc.GetRoomInfoResponse
	11, // 16: rpc.GameService.PlayerOperation:output_type -> rpc.PlayerOperationResponse
	13, // 17: rpc.GameService.PlayerOffline:output_type -> rpc.PlayerOfflineResponse
	15, // 18: rpc.GameService.GetGlobalRank:output_type -> rpc.GetGlobalRankResponse
	18, // 19: rpc.GameService.ClearMatchQueue:output_type -> rpc.ClearMatchQueueResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_proto_rpc_game_proto_init() }
func file_pkg_proto_rpc_game_proto_init() {
	if File_pkg_proto_rpc_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_rpc_game_proto_rawDesc), len(file_pkg_proto_rpc_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_rpc_game_proto_goTypes,
		DependencyIndexes: file_pkg_proto_rpc_game_proto_depIdxs,
		MessageInfos:      file_pkg_proto_rpc_game_proto_msgTypes,
	}.Build()
	File_pkg_proto_rpc_game_proto = out.File
	file_pkg_proto_rpc_game_proto_goTypes = nil
	file_pkg_proto_rpc_game_proto_depIdxs = nil
}
