// 网关推送服务 protobuf 定义
// 游戏服可通过 gRPC 调用网关，向指定房间或单个玩家主动推送消息

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: pkg/proto/rpc/gateway.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_PushToRoom_FullMethodName   = "/rpc.GatewayService/PushToRoom"
	GatewayService_PushToPlayer_FullMethodName = "/rpc.GatewayService/PushToPlayer"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayService 网关推送服务，提供房间广播和单推能力。
// 游戏服通过此服务向网关发起推送请求，网关将消息通过 WebSocket 转发给客户端。
type GatewayServiceClient interface {
	// PushToRoom 向指定房间所有玩家广播消息
	PushToRoom(ctx context.Context, in *PushToRoomRequest, opts ...grpc.CallOption) (*PushToRoomResponse, error)
	// PushToPlayer 向指定单个玩家发送消息
	PushToPlayer(ctx context.Context, in *PushToPlayerRequest, opts ...grpc.CallOption) (*PushToPlayerResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) PushToRoom(ctx context.Context, in *PushToRoomRequest, opts ...grpc.CallOption) (*PushToRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushToRoomResponse)
	err := c.cc.Invoke(ctx, GatewayService_PushToRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) PushToPlayer(ctx context.Context, in *PushToPlayerRequest, opts ...grpc.CallOption) (*PushToPlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushToPlayerResponse)
	err := c.cc.Invoke(ctx, GatewayService_PushToPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
//
// GatewayService 网关推送服务，提供房间广播和单推能力。
// 游戏服通过此服务向网关发起推送请求，网关将消息通过 WebSocket 转发给客户端。
type GatewayServiceServer interface {
	// PushToRoom 向指定房间所有玩家广播消息
	PushToRoom(context.Context, *PushToRoomRequest) (*PushToRoomResponse, error)
	// PushToPlayer 向指定单个玩家发送消息
	PushToPlayer(context.Context, *PushToPlayerRequest) (*PushToPlayerResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) PushToRoom(context.Context, *PushToRoomRequest) (*PushToRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushToRoom not implemented")
}
func (UnimplementedGatewayServiceServer) PushToPlayer(context.Context, *PushToPlayerRequest) (*PushToPlayerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushToPlayer not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_PushToRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushToRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).PushToRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_PushToRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).PushToRoom(ctx, req.(*PushToRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_PushToPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushToPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).PushToPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_PushToPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).PushToPlayer(ctx, req.(*PushToPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushToRoom",
			Handler:    _GatewayService_PushToRoom_Handler,
		},
		{
			MethodName: "PushToPlayer",
			Handler:    _GatewayService_PushToPlayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/rpc/gateway.proto",
}
