// 网关推送服务 protobuf 定义
// 游戏服可通过 gRPC 调用网关，向指定房间或单个玩家主动推送消息

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pkg/proto/rpc/gateway.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PushToRoomRequest 房间广播请求
type PushToRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 目标房间 ID
	MsgId         uint32                 `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`   // 消息 ID，对应 WebSocket 协议中的 MsgID
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                   // 消息体，由调用方序列化后的 protobuf 二进制数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToRoomRequest) Reset() {
	*x = PushToRoomRequest{}
	mi := &file_pkg_proto_rpc_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToRoomRequest) ProtoMessage() {}

func (x *PushToRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToRoomRequest.ProtoReflect.Descriptor instead.
func (*PushToRoomRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *PushToRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PushToRoomRequest) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *PushToRoomRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// PushToRoomResponse 房间广播响应
type PushToRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`   // 业务状态码，0 成功，非 0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`      // 提示信息
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` // 实际推送到的玩家数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToRoomResponse) Reset() {
	*x = PushToRoomResponse{}
	mi := &file_pkg_proto_rpc_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToRoomResponse) ProtoMessage() {}

func (x *PushToRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToRoomResponse.ProtoReflect.Descriptor instead.
func (*PushToRoomResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PushToRoomResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PushToRoomResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PushToRoomResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// PushToPlayerRequest 单推消息请求
type PushToPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 目标玩家 ID
	MsgId         uint32                 `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`          // 消息 ID，对应 WebSocket 协议中的 MsgID
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                          // 消息体，由调用方序列化后的 protobuf 二进制数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToPlayerRequest) Reset() {
	*x = PushToPlayerRequest{}
	mi := &file_pkg_proto_rpc_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToPlayerRequest) ProtoMessage() {}

func (x *PushToPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToPlayerRequest.ProtoReflect.Descriptor instead.
func (*PushToPlayerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *PushToPlayerRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PushToPlayerRequest) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *PushToPlayerRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// PushToPlayerResponse 单推消息响应
type PushToPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码，0 成功，非 0 失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToPlayerResponse) Reset() {
	*x = PushToPlayerResponse{}
	mi := &file_pkg_proto_rpc_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToPlayerResponse) ProtoMessage() {}

func (x *PushToPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToPlayerResponse.ProtoReflect.Descriptor instead.
func (*PushToPlayerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *PushToPlayerResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PushToPlayerResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pkg_proto_rpc_gateway_proto protoreflect.FileDescriptor

const file_pkg_proto_rpc_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/proto/rpc/gateway.proto\x12\x03rpc\"W\n" +
	"\x11PushToRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\rR\x05msgId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"P\n" +
	"\x12PushToRoomResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"]\n" +
	"\x13PushToPlayerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\rR\x05msgId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"<\n" +
	"\x14PushToPlayerResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\x94\x01\n" +
	"\x0eGatewayService\x12=\n" +
	"\n" +
	"PushToRoom\x12\x16.rpc.PushToRoomRequest\x1a\x17.rpc.PushToRoomResponse\x12C\n" +
	"\fPushToPlayer\x12\x18.rpc.PushToPlayerRequest\x1a\x19.rpc.PushToPlayerResponseB\x13Z\x11pkg/proto/rpc;rpcb\x06proto3"

var (
	file_pkg_proto_rpc_gateway_proto_rawDescOnce sync.Once
	file_pkg_proto_rpc_gateway_proto_rawDescData []byte
)

func file_pkg_proto_rpc_gateway_proto_rawDescGZIP() []byte {
	file_pkg_proto_rpc_gateway_proto_rawDescOnce.Do(func() {
		file_pkg_proto_rpc_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_rpc_gateway_proto_rawDesc), len(file_pkg_proto_rpc_gateway_proto_rawDesc)))
	})
	return file_pkg_proto_rpc_gateway_proto_rawDescData
}

var file_pkg_proto_rpc_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_rpc_gateway_proto_goTypes = []any{
	(*PushToRoomRequest)(nil),    // 0: rpc.PushToRoomRequest
	(*PushToRoomResponse)(nil),   // 1: rpc.PushToRoomResponse
	(*PushToPlayerRequest)(nil),  // 2: rpc.PushToPlayerRequest
	(*PushToPlayerResponse)(nil), // 3: rpc.PushToPlayerResponse
}
var file_pkg_proto_rpc_gateway_proto_depIdxs = []int32{
	0, // 0: rpc.GatewayService.PushToRoom:input_type -> rpc.PushToRoomRequest
	2, // 1: rpc.GatewayService.PushToPlayer:input_type -> rpc.PushToPlayerRequest
	1, // 2: rpc.GatewayService.PushToRoom:output_type -> rpc.PushToRoomResponse
	3, // 3: rpc.GatewayService.PushToPlayer:output_type -> rpc.PushToPlayerResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_rpc_gateway_proto_init() }
func file_pkg_proto_rpc_gateway_proto_init() {
	if File_pkg_proto_rpc_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_rpc_gateway_proto_rawDesc), len(file_pkg_proto_rpc_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_rpc_gateway_proto_goTypes,
		DependencyIndexes: file_pkg_proto_rpc_gateway_proto_depIdxs,
		MessageInfos:      file_pkg_proto_rpc_gateway_proto_msgTypes,
	}.Build()
	File_pkg_proto_rpc_gateway_proto = out.File
	file_pkg_proto_rpc_gateway_proto_goTypes = nil
	file_pkg_proto_rpc_gateway_proto_depIdxs = nil
}
